docRoot                   /usr/local/lsws/Example/html/NutriWeb/dist

errorlog $VH_ROOT/logs/error.log {
  useServer               0
  logLevel                ERROR
  rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
  rollingSize             10M
}

index  {
  useServer               0
  indexFiles              index.html
  autoIndex               0
}

extprocessor nodejs {
  type                    proxy
  address                 127.0.0.1:3001
  maxConns                100
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context /api {
  type                    proxy
  handler                 nodejs
  addDefaultCharset       off
}

context / {
  location                $DOC_ROOT
  allowBrowse             0
  
  rewrite  {
    enable                1
    rules                 <<<END_rules
RewriteCond %{REQUEST_URI} !^/api
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.html [L,QSA]
END_rules
  }
}

expires {
  enableExpires           1
  expiresDefault          A604800
  expiresByType           image/*=A2592000, text/css=A604800, application/javascript=A604800
}

enableGzip                1
enableBr                  1

vhssl  {
  keyFile                 /etc/letsencrypt/live/nutriai.online/privkey.pem
  certFile                /etc/letsencrypt/live/nutriai.online/fullchain.pem
  certChain               1
  enableECDHE             1
  renegProtection         1
  sslProtocol             24
  enableSpdy              15
  enableStapling          1
  ocspRespMaxAge          86400
}
