docRoot                   $VH_ROOT/html/nutriweb

index  {
  useServer               0
  indexFiles              index.html
}

errorlog $VH_ROOT/logs/error.log {
  useServer               0
  logLevel                WARN
  rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
  rollingSize             10M
  keepDays                30
}

scripthandler  {
  add lsapi:lsphp74 php
}

enableGzip              1
enableBrCompress        1

expires {
  enableExpires           1
  expiresByType           image/*=A31536000,text/css=A31536000,application/x-javascript=A31536000,application/javascript=A31536000,font/*=A31536000,application/x-font-ttf=A31536000
}

extraHeaders <<<END_extraHeaders
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com
END_extraHeaders

context / {
  allowBrowse             1
  rewrite  {
    enable                1
    rules                 RewriteCond %{REQUEST_FILENAME} !-f
    rules                 RewriteCond %{REQUEST_FILENAME} !-d
    rules                 RewriteRule ^(.*)$ /index.html [L,QSA]
  }
}
